on:
  pull_request:
    branches: [ master ]

jobs:
  pr-test:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-13
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: install android workload
      run: dotnet workload install android

    - name: restore
      run: dotnet restore OpenUtau.Desktop -r ${{ matrix.os.arch }}

    - name: test
      run: dotnet test OpenUtau.Test